.github/workflows/information.yml

Enhancement: Sniff

---

.github/workflows/context.yml

Enhancement: Dump contexts

---

.github/workflows/reference.yml

Enhancement: Show references

---

.github/workflows/php-information.yml

Fix: Rename workflow

---

.github/workflows/php-information.yml

Fix: Run workflow on push

---

.github/workflows/reference.yml

Enhancement: Show reference

---

.github/workflows/reference.yml

Enhancement: Indicate kind of build

---

.dependabot/config.yml
.github/settings.yml

Enhancement: Allow dependabot to automatically merge pull requests

---

composer.json
composer.lock

Fix: Downgrade phpunit/phpunit

---

.github/CODEOWNERS

Fix: Reduce scope of code owner

---

.github/workflows/continuous-deployment.yml

Enhancement: Automatically create release

---

.github/workflows/continuous-deployment.yml

Enhancement: Upload files

---

.github/workflows/continuous-deployment.yml

Fix: Checkout repository

---

.github/workflows/continuous-deployment.yml

Enhancement: Determine raw tag

---

.github/CODEOWNERS

Fix: Configure CODEOWNERS

---

.github/workflows/information-php.yml

Enhancement: Add PHP 7.4 to build matrix

---

composer.json
composer.lock

Fix: Install dependencies that are not up-to-date

---

.github/workflows/continuous-integration.yml

Fix: Reference

---

.github/settings.yml

Enhancement: Add environment label

---

.github/settings.yml
.github/workflows/inform-context.yml
.github/workflows/inform-system.yml
.github/workflows/integrate.yaml
.github/workflows/renew.yaml
.php_cs
composer.json
composer.lock

Fix: Reduce size of build matrix

---

.github/workflows/deployment-process.yaml
.github/workflows/deployment-staging-create.yaml
.github/workflows/deployment-staging-delete.yaml

Enhancement: Deployment

---

.github/workflows/deployment-production-create.yaml

Enhancement: Create deployment on merge to master

---

.github/workflows/deployment-staging-delete.yaml

Fix: Do not bother with matrix

---

.github/workflows/deployment-process.yaml
.github/workflows/deployment-staging-delete.yaml

Fix: Deactivate production environments

---

.github/workflows/deployment-process.yaml
.github/workflows/deployment-staging-delete.yaml

Fix: Destructuring

---

.github/workflows/deployment-process.yaml
.github/workflows/deployment-production-create.yaml
.github/workflows/deployment-staging-create.yaml

Enhancement: Provide and pass through environment URL

---

src/Example.php

Fix: Add property type declaration

---

.github/workflows/deployment-process.yaml

Fix: Keep previews sorted

---

.github/workflows/deployment-production-create.yaml
.github/workflows/deployment-staging-create.yaml

Fix: No need to check out entire history

---

.github/workflows/deployment-process.yaml

Fix: Rename variables

---

.github/workflows/deployment-process.yaml

Fix: Inline variable

---

.github/workflows/deployment-process.yaml

Enhancement: Assemble string using literals

---

.github/workflows/deployment-process.yaml
.github/workflows/deployment-production-create.yaml
.github/workflows/deployment-staging-create.yaml
.github/workflows/deployment-staging-delete.yaml

Enhancement: Extract variables

---

.github/workflows/deployment-process.yaml
.github/workflows/deployment-production-create.yaml
.github/workflows/deployment-staging-create.yaml
.github/workflows/deployment-staging-delete.yaml

Enhancement: Simplify

---

.github/workflows/deployment-process.yaml
.github/workflows/deployment-staging-delete.yaml

Fix: Paginate through all old deployments

---

.github/workflows/integrate.yaml

Fix: Merge jobs

---

.github/settings.yml
.github/workflows/integrate.yaml
.php_cs

Enhancement: Synchronize with ergebnis/php-library-template

---

.github/workflows/integrate.yaml

Fix: Indentation

---

.github/workflows/triage.yaml

Enhancement: Add label based on branch prefix

---

.github/workflows/merge.yaml

Enhancement: Add merge workflow

---

.github/settings.yml
.github/workflows/deployment-production-create.yaml
.github/workflows/inform-system.yml
.github/workflows/integrate.yaml

This PR
✊🏿 Black lives matter.

Fix: Use main as default branch name

---

.github/workflows/deployment-process.yaml
.github/workflows/deployment-production-create.yaml
.github/workflows/deployment-staging-create.yaml
.github/workflows/deployment-staging-delete.yaml
.github/workflows/inform-system.yml
.github/workflows/integrate.yaml
.github/workflows/prune.yaml
.github/workflows/renew.yaml
.github/workflows/triage.yaml

Fix: Use major.minor.patch versions for GitHub actions

---

.github/workflows/deployment-process.yaml
.github/workflows/inform-system.yml
.github/workflows/integrate.yaml
.github/workflows/prune.yaml
.github/workflows/renew.yaml

Fix: Use outdated versions

---

.github/workflows/deployment-process.yaml
.github/workflows/deployment-production-create.yaml
.github/workflows/deployment-staging-create.yaml
.github/workflows/deployment-staging-delete.yaml
.github/workflows/inform-system.yml
.github/workflows/integrate.yaml
.github/workflows/prune.yaml
.github/workflows/release.yaml
.github/workflows/renew.yaml
.github/workflows/triage.yaml

Fix: Remove quotes

---

.github/workflows/deployment-process.yaml
.github/workflows/deployment-production-create.yaml
.github/workflows/deployment-staging-create.yaml
.github/workflows/deployment-staging-delete.yaml
.github/workflows/inform-system.yml
.github/workflows/integrate.yaml
.github/workflows/prune.yaml
.github/workflows/release.yaml
.github/workflows/renew.yaml
.github/workflows/triage.yaml

Fix: Add quotes

---

.github/workflows/reproducer.yaml

This PR
Related to https://github.com/dependabot/dependabot-core/issues/2346.

Enhancement: Add workflow for reproducing error

---

.github/workflows/deployment-production-create.yaml
.github/workflows/integrate.yaml

This PR
💁‍♂️ For reference, see https://github.blog/changelog/2020-07-22-github-actions-better-support-for-alternative-default-branch-names/.

Enhancement: Use $default-branch macro

---

composer.json
composer.lock

Fix: Remove composer/semver

---

.github/workflows/context.yml

Enhancement: Dump context for workflow_run event

---

.github/CONTRIBUTING.md
README.md

Enhancement: List all workflows

---

composer.json
composer.lock

Fix: Require `composer/package-versions-deprecated`

---

test/Unit/ExampleTest.php
test/Util/Helper.php

Enhancement: Pull in `Helper` from `ergebnis/test-util`

---

composer.json
composer.lock
psalm-baseline.xml

Enhancement: Update `vimeo/psalm`

---

composer.json
composer.lock

Fix: Remove `composer/package-versions-deprecated`

---

psalm-baseline.xml
test/Unit/ExampleTest.php

Fix: Remove DocBlock

---

.github/actions/github/merge/action.yaml
.github/workflows/integrate.yaml

Enhancement: Extract composite action

---

.github/actions/github/merge/action.yaml
.github/workflows/integrate.yaml

Fix: Assignee
